meta_product_name: "YarnAlt"
meta_title: "YarnAlt - Find yarn alternatives to your projects"
meta_description: "The place to find yarn alternatives for your knitting and crochet projects "
meta_image: "knit_pool.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
